### ISSUE TITLE
Reset your password

### ISSUE THREAD

**Issue by Myjem** [xEdziu/RPG-Handy-Helper-Archived#17]
We need to create an UI for resetting a password. Im not sure if that should be a site or some sort of menu in the login page.

**Comment by Myjem** [comment]
damn you were faster in adding the milestone xdd

**Comment by xEdziu** [comment]
xdd
remember about quick deadline time, we will need this front for testing

**Comment by xEdziu** [comment]
@Myjem regarding the original comment, imo it should be separate site that should contain one input for the user's email

for more things regarding actions that will take place on this site, look up #9 issue in the todo section of forgot password
